pandoc2review articles/01_introduction.md > articles/01_introduction.re
pandoc2review articles/02_setting.md > articles/02_setting.re
pandoc2review articles/03_account.md > articles/03_account.re
pandoc2review articles/04_transaction.md > articles/04_transaction.re
pandoc2review articles/05_mosaic.md > articles/05_mosaic.re
pandoc2review articles/06_namespace.md > articles/06_namespace.re
pandoc2review articles/07_metadata.md > articles/07_metadata.re
pandoc2review articles/08_lock.md > articles/08_lock.re
pandoc2review articles/09_multisig.md > articles/09_multisig.re
pandoc2review articles/10_observer.md > articles/10_observer.re
pandoc2review articles/11_restriction.md > articles/11_restriction.re
pandoc2review articles/12_offline_signature.md > articles/12_offline_signature.re
pandoc2review articles/13_verify.md > articles/13_verify.re
